services:
  # -- Database ---------------------------------------------
  b2c_postgresql:
    env_file: .env
    image: postgres:latest
    container_name: "b2c_database"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - ./b2c_postgres_data:/var/lib/postgresql
    ports:
      - "${DB_PORT}:${DB_PORT}"

  # -- App ---------------------------------------------------
  b2c_app:
    build: .
    container_name: b2c_app
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: b2c_postgresql
    depends_on:
      - b2c_postgresql
    restart: unless-stopped

volumes:
  b2c_postgres_data:
