"""ref

Revision ID: 2d364a354e20
Revises: 2ee49090ce6d
Create Date: 2026-05-02 07:03:04.063059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d364a354e20'
down_revision: Union[str, Sequence[str], None] = '2ee49090ce6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.add_column('carts', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.alter_column('carts', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('carts_buyer_id_key'), 'carts', type_='unique')
    op.create_index(op.f('ix_carts_session_id'), 'carts', ['session_id'], unique=False)
    op.drop_column('favorites', 'notify_price_down')
    op.drop_column('favorites', 'notify_in_stock')
    op.drop_column('favorites', 'baseline_price')
    op.add_column('order_items', sa.Column('product_title', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('unit_price', sa.BigInteger(), nullable=False))
    op.add_column('order_items', sa.Column('line_total', sa.BigInteger(), nullable=False))
    op.drop_column('order_items', 'price')
    op.add_column('orders', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_column('orders', 'idempotency_key')
    op.add_column('order_items', sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'line_total')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'product_title')
    op.add_column('favorites', sa.Column('baseline_price', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('notify_in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('favorites', sa.Column('notify_price_down', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_carts_session_id'), table_name='carts')
    op.create_unique_constraint(op.f('carts_buyer_id_key'), 'carts', ['buyer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('carts', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('carts', 'session_id')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_column('cart_items', 'product_id')
    # ### end Alembic commands ###
