"""add product_subscriptions table

Revision ID: 6212a4161e2c
Revises: 189a96a94488
Create Date: 2026-05-02 07:18:33.857844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6212a4161e2c'
down_revision: Union[str, Sequence[str], None] = '189a96a94488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('notify_on', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='user_product_subscription')
    )
    op.create_index(op.f('ix_product_subscriptions_product_id'), 'product_subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_subscriptions_user_id'), 'product_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_subscriptions_user_id'), table_name='product_subscriptions')
    op.drop_index(op.f('ix_product_subscriptions_product_id'), table_name='product_subscriptions')
    op.drop_table('product_subscriptions')
    # ### end Alembic commands ###
