"""add missing fields to buyers

Revision ID: dd3d672c8042
Revises: 6212a4161e2c
Create Date: 2026-05-22 00:26:23.065152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd3d672c8042'
down_revision: Union[str, Sequence[str], None] = '6212a4161e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_events_idempotency_key'), 'b2b_events', ['idempotency_key'], unique=False)
    op.add_column('addresses', sa.Column('region', sa.String(length=200), nullable=True))
    op.add_column('addresses', sa.Column('recipient_name', sa.String(length=200), nullable=True))
    op.add_column('addresses', sa.Column('recipient_phone', sa.String(length=20), nullable=True))
    op.add_column('addresses', sa.Column('comment', sa.String(length=500), nullable=True))
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('addresses', 'street',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('addresses', 'building',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('addresses', 'apartment',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('buyers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.alter_column('buyers', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('order_items', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('sku_code', sa.String(length=100), nullable=True))
    op.drop_column('order_items', 'product_title')
    op.drop_column('order_items', 'sku_name')
    op.add_column('orders', sa.Column('idempotency_body_hash', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('payment_method_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('number', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.BigInteger(), nullable=False))
    op.add_column('orders', sa.Column('delivery_cost', sa.BigInteger(), nullable=False))
    op.add_column('orders', sa.Column('total', sa.BigInteger(), nullable=False))
    op.add_column('orders', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_foreign_key(None, 'orders', 'payment_methods', ['payment_method_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'total_price')
    op.add_column('payment_methods', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('payment_methods', sa.Column('card_last4', sa.String(length=4), nullable=True))
    op.add_column('payment_methods', sa.Column('card_brand', sa.String(length=20), nullable=True))
    op.drop_column('payment_methods', 'last4')
    op.drop_column('payment_methods', 'exp_month')
    op.drop_column('payment_methods', 'exp_year')
    op.drop_column('payment_methods', 'cardholder_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('cardholder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('payment_methods', sa.Column('exp_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment_methods', sa.Column('exp_month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment_methods', sa.Column('last4', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('payment_methods', 'card_brand')
    op.drop_column('payment_methods', 'card_last4')
    op.drop_column('payment_methods', 'type')
    op.add_column('orders', sa.Column('total_price', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'status_history')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'delivery_cost')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'number')
    op.drop_column('orders', 'payment_method_id')
    op.drop_column('orders', 'idempotency_body_hash')
    op.add_column('order_items', sa.Column('sku_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('product_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'sku_code')
    op.drop_column('order_items', 'name')
    op.alter_column('buyers', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('buyers', 'date_of_birth')
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('addresses', 'apartment',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('addresses', 'building',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('addresses', 'street',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('addresses', 'comment')
    op.drop_column('addresses', 'recipient_phone')
    op.drop_column('addresses', 'recipient_name')
    op.drop_column('addresses', 'region')
    op.drop_index(op.f('ix_b2b_events_idempotency_key'), table_name='b2b_events')
    op.drop_table('b2b_events')
    # ### end Alembic commands ###
