"""save init price in cart

Revision ID: df29111563c8
Revises: 14017dceacbe
Create Date: 2026-05-31 01:47:43.649370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df29111563c8'
down_revision: Union[str, Sequence[str], None] = '14017dceacbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('unit_price_at_add', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'unit_price_at_add')
    # ### end Alembic commands ###
